# Setup
title:               Echos Du Futur Perdu
tagline:             'Echoes of the Lost Future'
description:         
url:                 
baseurl:             
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Echos Du Futur Perdu
  url:               https://echosdufuturperdu.github.io
  email:             echosdufuturperdu@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
